name: milkcollection
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.2
  cupertino_icons: ^1.0.2
  datetime_picker_formfield_new: ^2.1.0
  excel: ^4.0.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  share_plus: null
  sn_progress_dialog: ^1.1.4
  sqflite: ^2.3.0
  upgrader: ^10.1.0
  open_filex: ^4.4.0

  flutter_sms_android: ^2.3.7
  internet_connection_checker_plus: ^2.3.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "#ffffff"
  # adaptive_icon_foreground: "assets/images/icon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
